/**
 * Format review comments for GitHub
 * @param {Array} issues - Array of issues from AI analysis
 * @returns {string} - Formatted markdown comment
 */
function formatReviewComment(issues) {
  if (!issues || issues.length === 0) {
    return '## Code Review\n\nNo issues found. Great work! 🎉';
  }

  // Group issues by severity
  const high = issues.filter(i => i.severity === 'high');
  const medium = issues.filter(i => i.severity === 'medium');
  const low = issues.filter(i => i.severity === 'low');

  let comment = '## AI Code Review 🤖\n\n';

  // Summary
  comment += `Found ${issues.length} issue(s): ${high.length} high, ${medium.length} medium, ${low.length} low\n\n`;

  // High severity
  if (high.length > 0) {
    comment += '### 🚨 High Priority\n\n';
    high.forEach((issue, index) => {
      comment += formatIssue(issue, index + 1);
    });
    comment += '\n';
  }

  // Medium severity
  if (medium.length > 0) {
    comment += '### ⚠️ Medium Priority\n\n';
    const startIndex = high.length + 1;
    medium.forEach((issue, index) => {
      comment += formatIssue(issue, startIndex + index);
    });
    comment += '\n';
  }

  // Low severity
  if (low.length > 0) {
    comment += '### 💡 Low Priority / Suggestions\n\n';
    const startIndex = high.length + medium.length + 1;
    low.forEach((issue, index) => {
      comment += formatIssue(issue, startIndex + index);
    });
  }

  // Footer
  comment += '\n---\n*This review was generated by AI. Please verify suggestions before applying.*';

  return comment;
}

/**
 * Format a single issue
 * @param {object} issue - Issue object
 * @param {number} index - Issue number
 * @returns {string} - Formatted issue
 */
function formatIssue(issue, index) {
  const icon = getIcon(issue.type);
  let formatted = `${index}. ${icon} **${issue.type.toUpperCase()}**`;

  if (issue.file) {
    formatted += ` in \`${issue.file}\``;
    if (issue.line) {
      formatted += `:${issue.line}`;
    }
  }

  formatted += `\n   - ${issue.description}\n`;

  if (issue.suggestion) {
    formatted += `   - 💡 **Suggestion:** ${issue.suggestion}\n`;
  }

  return formatted + '\n';
}

/**
 * Get icon for issue type
 * @param {string} type - Issue type
 * @returns {string} - Emoji icon
 */
function getIcon(type) {
  const icons = {
    bug: '🐛',
    security: '🔒',
    performance: '⚡',
    style: '🎨',
    suggestion: '💡'
  };
  return icons[type] || '📝';
}

module.exports = {
  formatReviewComment
};
