package formatter

import "fmt"

// Issue represents a code review issue
type Issue struct {
	Type        string `json:"type"`
	Severity    string `json:"severity"`
	File        string `json:"file,omitempty"`
	Line        int    `json:"line,omitempty"`
	Description string `json:"description"`
	Suggestion  string `json:"suggestion,omitempty"`
}

// FormatReviewComment formats review issues as a GitHub comment
func FormatReviewComment(issues []Issue) string {
	if len(issues) == 0 {
		return "## Code Review\n\nNo issues found. Great work! 🎉"
	}

	// Group issues by severity
	var high, medium, low []Issue
	for _, issue := range issues {
		switch issue.Severity {
		case "high":
			high = append(high, issue)
		case "medium":
			medium = append(medium, issue)
		case "low":
			low = append(low, issue)
		default:
			low = append(low, issue)
		}
	}

	comment := "## AI Code Review 🤖\n\n"

	// Summary
	comment += fmt.Sprintf("Found %d issue(s): %d high, %d medium, %d low\n\n", 
		len(issues), len(high), len(medium), len(low))

	// High severity
	if len(high) > 0 {
		comment += "### 🚨 High Priority\n\n"
		for i, issue := range high {
			comment += formatIssue(issue, i+1)
		}
		comment += "\n"
	}

	// Medium severity
	if len(medium) > 0 {
		comment += "### ⚠️ Medium Priority\n\n"
		startIdx := len(high) + 1
		for i, issue := range medium {
			comment += formatIssue(issue, startIdx+i)
		}
		comment += "\n"
	}

	// Low severity
	if len(low) > 0 {
		comment += "### 💡 Low Priority / Suggestions\n\n"
		startIdx := len(high) + len(medium) + 1
		for i, issue := range low {
			comment += formatIssue(issue, startIdx+i)
		}
	}

	// Footer
	comment += "\n---\n*This review was generated by AI. Please verify suggestions before applying.*"

	return comment
}

// formatIssue formats a single issue
func formatIssue(issue Issue, index int) string {
	icon := getIcon(issue.Type)
	formatted := fmt.Sprintf("%d. %s **%s**", index, icon, issue.Type)

	if issue.File != "" {
		formatted += fmt.Sprintf(" in `%s`", issue.File)
		if issue.Line > 0 {
			formatted += fmt.Sprintf(":%d", issue.Line)
		}
	}

	formatted += fmt.Sprintf("\n   - %s\n", issue.Description)

	if issue.Suggestion != "" {
		formatted += fmt.Sprintf("   - 💡 **Suggestion:** %s\n", issue.Suggestion)
	}

	return formatted + "\n"
}

// getIcon returns emoji icon for issue type
func getIcon(issueType string) string {
	icons := map[string]string{
		"bug":        "🐛",
		"security":   "🔒",
		"performance": "⚡",
		"style":      "🎨",
		"suggestion": "💡",
	}
	if icon, ok := icons[issueType]; ok {
		return icon
	}
	return "📝"
}
